package models

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

//all data points that we'll send are pointers
//it's just a good practice
// ID will be generated by system so no pointer for it

type Entry struct {
	ID          primitive.ObjectID `bson:"_id,omitempty"`
	Dish        *string            `json:"dish"`
	Fat         *string          `json:"fat"`
	Ingredients *string            `json:"ingredients"`
	Calories    *string            `json:"calories"`
	Protein     *string          `json:"protein"`
	Carbohydrates *string        `json:"carbohydrates"`
}

